# -*- coding: utf-8 -*-
"""...

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15NtiePRxy-gjVH35jp-4FYoluvBWLxo9
"""

from scipy.constants import c,h,k
from math import pi, e
import matplotlib.pyplot as plt
import numpy as np

T = 6000
nu = np.linspace(0.1,2000,100)*1e12

Sv = (2*h*nu**3)/((c**2)*(e**(h*nu/(k*T))-1))*1e9

plt.plot(nu, Sv)

plt.xlabel('Frequency [THz]')
plt.ylabel('Surface brightness [nW sr$^{-1}$ m$^{-2}$ Hz$^{-1}$]');

plt.grid(); plt.legend();